apiVersion: apps/v1
kind: Deployment
metadata:
  name: hogwarts-bot
  namespace: hogwarts-bot
spec:
  selector:
    matchLabels:
      app: bot
  replicas: 1
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - name: bot
        image: hogwarts-bot
        imagePullPolicy: Never
        volumeMounts:
        - name: secrets
          mountPath: "/app/secrets"
          readOnly: true
      volumes:
      - name: secrets
        secret:
           secretName: hogwarts-secrets